sudo: false
language: bash

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc

script:
    # Ignoring SC2207 because word splitting works the way it's wanted to, and
    # SC2155 is ignored because the return values from $() expressions aren't
    # needed. No `local foo=$(false) || echo foo;` expresions are used anyway.
  - bash -c 'shopt -s globstar nullglob; shellcheck -e SC2207 -e SC2155 **/*.{sh,ksh,bash}'
    # Running the tests file
  - bats tests.bash

notifications:
    email: false
